# Generated by Django 4.1.6 on 2023-02-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="voting.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voting_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="voting.votinguser",
            ),
        ),
    ]
