# Generated by Django 4.1.6 on 2023-02-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0002_alter_vote_restaurant_alter_vote_voting_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="voting_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="voting.votinguser",
            ),
        ),
        migrations.AlterField(
            model_name="votinguser",
            name="username",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
